# refs: https://github.com/realm/SwiftLint/blob/master/Rules.md

reporter: "xcode"

included:
  - WKJavaScriptController
  - WKJavaScriptController-Demo

excluded:
  - WKJavaScriptController-Demo/Pods

disabled_rules:
  - block_based_kvo # Prefer the new block based KVO API with keypaths when using Swift 3.2 or later.
  - cyclomatic_complexity # Complexity of function bodies should be limited.
  - file_length # Files should not span too many lines.
  - for_where # where clauses are preferred over a single if inside a for.
  - force_cast # Force casts should be avoided.
  - force_try # Force tries should be avoided.
  - function_body_length # Functions bodies should not span too many lines.
  - line_length # Lines should not span too many characters.
  - todo # TODOs and FIXMEs should be resolved.
  - trailing_whitespace # Lines should not have trailing whitespace.

opt_in_rules:
  - array_init # Prefer using Array(seq) over seq.map { $0 } to convert a sequence into an Array.
  - closure_end_indentation # Closure end should have the same indentation as the line that started it.
  - closure_spacing # Closure expressions should have a single space inside each brace.
  - conditional_returns_on_newline # Conditional statements should always return on the next line.
  - discouraged_optional_boolean # Prefer non-optional booleans over optional booleans.
  - empty_count # Prefer checking isEmpty over comparing count to zero.
  - empty_string # Prefer checking isEmpty over comparing string to an empty string literal.
  - empty_xctest_method # Empty XCTest method should be avoided.
  - explicit_init # Explicitly calling .init() should be avoided.
  - extension_access_modifier # Prefer to use extension access modifiers.
  - fallthrough # Fallthrough should be avoided.
  - fatal_error_message # A fatalError call should have a message.
  - file_header # Header comments should be consistent with project patterns.
  - first_where # Prefer using .first(where:) over .filter { }.first in collections.
  - function_default_parameter_at_end # Prefer to locate parameters with defaults toward the end of the parameter list.
  - joined_default_parameter # Discouraged explicit usage of the default. separator.
  - literal_expression_end_indentation # Array and dictionary literal end should have the same indentation as the line that started it.
  - lower_acl_than_parent # Ensure definitions have a lower access control level than their enclosing parent.
  - modifier_order # Modifier order should be consistent.
  - prohibited_super_call # Some methods should not call super.
  - sorted_imports # Imports should be sorted.
  - vertical_parameter_alignment_on_call # Function parameters should be aligned vertically if they're in multiple lines in a method call.
  - unneeded_parentheses_in_closure_argument # Parentheses are not needed when declaring closure arguments.

function_parameter_count:
  warning: 11
  error: 11

identifier_name:
  max_length:
    warning: 50
    error: 50
  min_length:
    warning: 1
    error: 1
